# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'InventoryEdit.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_itemEditor(object):
    def setupUi(self, itemEditor):
        itemEditor.setObjectName("itemEditor")
        itemEditor.resize(500, 574)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("dwlogo.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        itemEditor.setWindowIcon(icon)
        self.gridLayout_2 = QtWidgets.QGridLayout(itemEditor)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.speichernButton = QtWidgets.QPushButton(itemEditor)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.speichernButton.setFont(font)
        self.speichernButton.setToolTipDuration(0)
        self.speichernButton.setObjectName("speichernButton")
        self.gridLayout_2.addWidget(self.speichernButton, 1, 1, 1, 1)
        self.abbrechenButton = QtWidgets.QPushButton(itemEditor)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.abbrechenButton.setFont(font)
        self.abbrechenButton.setToolTipDuration(0)
        self.abbrechenButton.setObjectName("abbrechenButton")
        self.gridLayout_2.addWidget(self.abbrechenButton, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(itemEditor)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.mengeText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mengeText.sizePolicy().hasHeightForWidth())
        self.mengeText.setSizePolicy(sizePolicy)
        self.mengeText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.mengeText.setFont(font)
        self.mengeText.setObjectName("mengeText")
        self.gridLayout.addWidget(self.mengeText, 1, 0, 1, 1)
        self.gewicht = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gewicht.sizePolicy().hasHeightForWidth())
        self.gewicht.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gewicht.setFont(font)
        self.gewicht.setObjectName("gewicht")
        self.gridLayout.addWidget(self.gewicht, 2, 1, 1, 1)
        self.geschickText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geschickText.sizePolicy().hasHeightForWidth())
        self.geschickText.setSizePolicy(sizePolicy)
        self.geschickText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.geschickText.setFont(font)
        self.geschickText.setObjectName("geschickText")
        self.gridLayout.addWidget(self.geschickText, 5, 0, 1, 1)
        self.weisheitText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weisheitText.sizePolicy().hasHeightForWidth())
        self.weisheitText.setSizePolicy(sizePolicy)
        self.weisheitText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.weisheitText.setFont(font)
        self.weisheitText.setObjectName("weisheitText")
        self.gridLayout.addWidget(self.weisheitText, 8, 0, 1, 1)
        self.konstitution = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.konstitution.sizePolicy().hasHeightForWidth())
        self.konstitution.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.konstitution.setFont(font)
        self.konstitution.setObjectName("konstitution")
        self.gridLayout.addWidget(self.konstitution, 6, 1, 1, 1)
        self.weisheit = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.weisheit.sizePolicy().hasHeightForWidth())
        self.weisheit.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.weisheit.setFont(font)
        self.weisheit.setObjectName("weisheit")
        self.gridLayout.addWidget(self.weisheit, 8, 1, 1, 1)
        self.menge = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menge.sizePolicy().hasHeightForWidth())
        self.menge.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.menge.setFont(font)
        self.menge.setObjectName("menge")
        self.gridLayout.addWidget(self.menge, 1, 1, 1, 1)
        self.staerkeText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.staerkeText.sizePolicy().hasHeightForWidth())
        self.staerkeText.setSizePolicy(sizePolicy)
        self.staerkeText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.staerkeText.setFont(font)
        self.staerkeText.setObjectName("staerkeText")
        self.gridLayout.addWidget(self.staerkeText, 4, 0, 1, 1)
        self.staerke = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.staerke.sizePolicy().hasHeightForWidth())
        self.staerke.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.staerke.setFont(font)
        self.staerke.setObjectName("staerke")
        self.gridLayout.addWidget(self.staerke, 4, 1, 1, 1)
        self.geschick = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.geschick.sizePolicy().hasHeightForWidth())
        self.geschick.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.geschick.setFont(font)
        self.geschick.setObjectName("geschick")
        self.gridLayout.addWidget(self.geschick, 5, 1, 1, 1)
        self.konstitutionText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.konstitutionText.sizePolicy().hasHeightForWidth())
        self.konstitutionText.setSizePolicy(sizePolicy)
        self.konstitutionText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.konstitutionText.setFont(font)
        self.konstitutionText.setObjectName("konstitutionText")
        self.gridLayout.addWidget(self.konstitutionText, 6, 0, 1, 1)
        self.intelligenzText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intelligenzText.sizePolicy().hasHeightForWidth())
        self.intelligenzText.setSizePolicy(sizePolicy)
        self.intelligenzText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.intelligenzText.setFont(font)
        self.intelligenzText.setObjectName("intelligenzText")
        self.gridLayout.addWidget(self.intelligenzText, 7, 0, 1, 1)
        self.gewichtText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.gewichtText.sizePolicy().hasHeightForWidth())
        self.gewichtText.setSizePolicy(sizePolicy)
        self.gewichtText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gewichtText.setFont(font)
        self.gewichtText.setObjectName("gewichtText")
        self.gridLayout.addWidget(self.gewichtText, 2, 0, 1, 1)
        self.intelligenz = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.intelligenz.sizePolicy().hasHeightForWidth())
        self.intelligenz.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.intelligenz.setFont(font)
        self.intelligenz.setObjectName("intelligenz")
        self.gridLayout.addWidget(self.intelligenz, 7, 1, 1, 1)
        self.charismaText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charismaText.sizePolicy().hasHeightForWidth())
        self.charismaText.setSizePolicy(sizePolicy)
        self.charismaText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.charismaText.setFont(font)
        self.charismaText.setObjectName("charismaText")
        self.gridLayout.addWidget(self.charismaText, 9, 0, 1, 1)
        self.charisma = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.charisma.sizePolicy().hasHeightForWidth())
        self.charisma.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.charisma.setFont(font)
        self.charisma.setObjectName("charisma")
        self.gridLayout.addWidget(self.charisma, 9, 1, 1, 1)
        self.ruestung = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ruestung.sizePolicy().hasHeightForWidth())
        self.ruestung.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ruestung.setFont(font)
        self.ruestung.setObjectName("ruestung")
        self.gridLayout.addWidget(self.ruestung, 10, 1, 1, 1)
        self.ruestungText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ruestungText.sizePolicy().hasHeightForWidth())
        self.ruestungText.setSizePolicy(sizePolicy)
        self.ruestungText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.ruestungText.setFont(font)
        self.ruestungText.setObjectName("ruestungText")
        self.gridLayout.addWidget(self.ruestungText, 10, 0, 1, 1)
        self.belastung = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.belastung.sizePolicy().hasHeightForWidth())
        self.belastung.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.belastung.setFont(font)
        self.belastung.setObjectName("belastung")
        self.gridLayout.addWidget(self.belastung, 13, 1, 1, 1)
        self.leben = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leben.sizePolicy().hasHeightForWidth())
        self.leben.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.leben.setFont(font)
        self.leben.setObjectName("leben")
        self.gridLayout.addWidget(self.leben, 12, 1, 1, 1)
        self.schadenText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schadenText.sizePolicy().hasHeightForWidth())
        self.schadenText.setSizePolicy(sizePolicy)
        self.schadenText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.schadenText.setFont(font)
        self.schadenText.setObjectName("schadenText")
        self.gridLayout.addWidget(self.schadenText, 11, 0, 1, 1)
        self.schaden = QtWidgets.QSpinBox(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.schaden.sizePolicy().hasHeightForWidth())
        self.schaden.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.schaden.setFont(font)
        self.schaden.setObjectName("schaden")
        self.gridLayout.addWidget(self.schaden, 11, 1, 1, 1)
        self.lebenText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lebenText.sizePolicy().hasHeightForWidth())
        self.lebenText.setSizePolicy(sizePolicy)
        self.lebenText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.lebenText.setFont(font)
        self.lebenText.setObjectName("lebenText")
        self.gridLayout.addWidget(self.lebenText, 12, 0, 1, 1)
        self.belastungText = QtWidgets.QLabel(self.frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.belastungText.sizePolicy().hasHeightForWidth())
        self.belastungText.setSizePolicy(sizePolicy)
        self.belastungText.setMinimumSize(QtCore.QSize(400, 0))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.belastungText.setFont(font)
        self.belastungText.setObjectName("belastungText")
        self.gridLayout.addWidget(self.belastungText, 13, 0, 1, 1)
        self.beschreibung = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.beschreibung.setFont(font)
        self.beschreibung.setObjectName("beschreibung")
        self.gridLayout.addWidget(self.beschreibung, 3, 0, 1, 3)
        self.gegenstand = QtWidgets.QLineEdit(self.frame)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.gegenstand.setFont(font)
        self.gegenstand.setObjectName("gegenstand")
        self.gridLayout.addWidget(self.gegenstand, 0, 0, 1, 3)
        self.gridLayout_2.addWidget(self.frame, 0, 1, 1, 2)

        self.retranslateUi(itemEditor)
        QtCore.QMetaObject.connectSlotsByName(itemEditor)

    def retranslateUi(self, itemEditor):
        _translate = QtCore.QCoreApplication.translate
        itemEditor.setWindowTitle(_translate("itemEditor", "Dungeon World Item Editor"))
        self.speichernButton.setToolTip(_translate("itemEditor", "Speichert die aktuellen Daten in einem Item"))
        self.speichernButton.setText(_translate("itemEditor", "Speichern"))
        self.abbrechenButton.setToolTip(_translate("itemEditor", "Bricht den Vorgang zum erstellen eines neuen Items ab"))
        self.abbrechenButton.setText(_translate("itemEditor", "Abbrechen"))
        self.mengeText.setText(_translate("itemEditor", "Menge"))
        self.geschickText.setText(_translate("itemEditor", "Geschick"))
        self.weisheitText.setText(_translate("itemEditor", "Weisheit"))
        self.staerkeText.setText(_translate("itemEditor", "Stärke"))
        self.konstitutionText.setText(_translate("itemEditor", "Konstitution"))
        self.intelligenzText.setText(_translate("itemEditor", "Intelligenz"))
        self.gewichtText.setText(_translate("itemEditor", "Gewicht"))
        self.charismaText.setText(_translate("itemEditor", "Charisma"))
        self.ruestungText.setText(_translate("itemEditor", "Rüstung"))
        self.schadenText.setText(_translate("itemEditor", "Schaden"))
        self.lebenText.setText(_translate("itemEditor", "Leben"))
        self.belastungText.setText(_translate("itemEditor", "Belastung"))
        self.beschreibung.setPlaceholderText(_translate("itemEditor", "Beschreibung"))
        self.gegenstand.setPlaceholderText(_translate("itemEditor", "Gegenstand"))

